### ISSUE TITLE
Gnome 42 Shell Applet Menu Background Colour

### ISSUE THREAD

**Issue by rakshithbegane** [EliverLara/Sweet#194]
I have recently upgraded to gnome 42, after the update background color on the applet menu follows the default gnome-shell theme color not the "Sweet Dark" theme color standard. See the attached screenshots 

![Screenshot from 2022-04-17 21-34-30](https://user-images.githubusercontent.com/1982699/163722763-e536d5b0-5a6b-4809-8888-5ba827c3268e.png)
![Screenshot from 2022-04-17 21-33-50](https://user-images.githubusercontent.com/1982699/163722764-c4bb852e-2dc7-4d20-acde-e345434b93cf.png)

**Comment by xukashi** [comment]
+1

**Comment by artforlife** [comment]
I second this. Here is a screenshot from me.

![image](https://user-images.githubusercontent.com/8064423/164973292-80f2efb9-dcbc-43b2-a379-503831427764.png)

**Comment by artforlife** [comment]
I second this. Here is another screenshot.

![image](https://user-images.githubusercontent.com/8064423/164973317-2c28b913-939b-4a6c-be3e-9cf66acf48c0.png)

**Comment by PROxZIMA** [comment]
Looking at the commit history I tried the updated `sweet-dark-v40.tar.xz` from `pling` on `Gnome 42.1` and this issue is fixed!!

![1](https://user-images.githubusercontent.com/43103163/169680668-bbd1cd91-2aae-414c-bc42-9935af9ac32d.png)
![2](https://user-images.githubusercontent.com/43103163/169680670-e8f44b82-e3fe-49f7-9acb-6396d08fbc60.png)

**Comment by serpro69** [comment]
Unfortunately this is still not fixed for me :( @PROxZIMA , do you have anything else installed that controls the theme or maybe fixes this issue?
I have a fresh ubuntu 22.04 with gnome 42.1 and still getting the same issue even though I'm using the latest version of the theme. I've tried the Sweet-Dark-v40 version from pling (and gnome-look.org, although of course the files are exactly the same...)
