### ISSUE TITLE
Transparent menubar

### ISSUE THREAD

**Issue by Zzombiee2361** [EliverLara/Sweet#49]
Hi, I'm using Sweet-transparent-toolbar kvantum theme. The theme made menubar transparent but only if there's a toolbar. Is it possible for you to make the menubar transparent even without toolbar?

**Comment by EliverLara** [comment]
Done!

**Comment by Zzombiee2361** [comment]
![image](https://user-images.githubusercontent.com/37852137/65243447-9360ce00-db12-11e9-955c-75491195a306.png)
It's fixed for some application, but the issue still persist on konsole. This is the reason I made this issue in the first place, as you can see the menubar looks out of place with all the blur around it

**Comment by EliverLara** [comment]
@Zzombiee2361  It seems that Konsole uses the 'window' element for its menubar, so it is almost impossible to make it transparent without affecting other UI elements, I would recommend hiding the menu bar (`ctrl+shift+m`), but if you really need it to be present  you can do the trick for yourself by doing the following:

1. Open the config file (`~/.config/Kvantum/Sweet-transparent-toolbar/Sweet-transparent-toolbar.kvconfig`)
2. Replace the `window.color` key from `#161925` to `#16192582` on line **76**
3. Replace the `interior.element` key from `window` to `_window` on line **493**
4. Save and reload the theme

**Comment by Zzombiee2361** [comment]
Well, thanks for the explanation. I'm not doing the workaround, I don't want to modify other UI element
